# Generated by Django 6.1.1 on 2026-09-22 16:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloTecnologico',
            fields=[
                ('idArticulo', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('audifonos', 'Audífonos'), ('tablet', 'Tablet'), ('notebook', 'Notebook')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('idEstudiante', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreCompleto', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12)),
                ('correoInstitucional', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('idLibro', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=150)),
                ('anioPublicacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('idProfesor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('idUsuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('jefe', 'Jefe de biblioteca'), ('bibliotecario', 'Bibliotecario'), ('practicante', 'Practicante')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('idPrestamo', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechaPrestamo', models.DateField()),
                ('fechaVencimiento', models.DateField()),
                ('fechaDevolucion', models.DateField(blank=True, null=True)),
                ('estadoPrestamo', models.CharField(choices=[('activo', 'Activo'), ('atrasado', 'Atrasado'), ('devuelto', 'Devuelto')], default='activo', max_length=20)),
                ('articuloTecnologico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='apiproyec.articulotecnologico')),
                ('devolucionRegistradaPor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devolucionesRegistradas', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='apiproyec.estudiante')),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='apiproyec.libro')),
                ('registradoPor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamosRegistrados', to=settings.AUTH_USER_MODEL)),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='apiproyec.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Restriccion',
            fields=[
                ('idRestriccion', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipoRestriccion', models.CharField(choices=[('libro', 'Libro'), ('tecnologico', 'Artículo tecnológico')], max_length=20)),
                ('fechaRestriccion', models.DateField()),
                ('estadoRestriccion', models.CharField(choices=[('activa', 'Activa'), ('retirada', 'Retirada')], default='activa', max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restricciones', to='apiproyec.estudiante')),
            ],
        ),
    ]
