# Generated by Django 6.1.1 on 2026-09-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiproyec', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='anioPublicacion',
            new_name='añoPublicacion',
        ),
    ]
