# Generated by Django 6.1.1 on 2026-09-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiproyec', '0002_rename_aniopublicacion_libro_añopublicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='añoPublicacion',
            new_name='año_Publicacion',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
