# Generated by Django 6.1.1 on 2026-09-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiproyec', '0003_rename_añopublicacion_libro_año_publicacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='correoInstitucional',
            new_name='correo_Institucional',
        ),
    ]
