# Generated by Django 6.1.1 on 2026-09-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiproyec', '0004_rename_correoinstitucional_estudiante_correo_institucional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='nombreCompleto',
            new_name='nombre_Completo',
        ),
    ]
